name: ez_validator
description: Dead simple field/object schema validation for flutter,EzValidator api is inspired by Yup/Zod
version: 0.3.7
homepage: https://github.com/X-SLAYER/EzValidator
documentation: https://github.com/X-SLAYER/EzValidator#methods

environment:
  sdk: ">=3.0.1 <4.0.0"

dev_dependencies:
  test: ^1.16.8
  flutter_lints: ^3.0.1
